### PR TITLE
Bring sailfish up to parity with marlin

### PR DESCRIPTION
**Pull request by NZedPred**
Currently sailfish (Google Pixel) only builds on the lineage_sailfish target, but not omni_sailfish.

These commits are to add the omni_sailfish- target, and bring the sailfish BoardConfig up to feature parity with marlin.

I have also noted that under lineage_sailfish, trying to add the additional flags to BoardConfig (e.g. TW_INCLUDE_REPACKTOOLS) results in a blank screen and forced reboot. A build under omni_sailfish works correctly with these flags.

So adding the omni_sailfish target appears to be the best option.

### CODE REVIEW

**Comment by bigbiff** [comment]
Hello, this will need to be pushed to our gerrit instance at gerrit.twrp.me for merging and review.

**Comment by NZedPred** [comment]
> Hello, this will need to be pushed to our gerrit instance at gerrit.twrp.me for merging and review.

Hi @bigbiff - the android-9.0 branch isn't available on gerrit. I see the repository, but the only branch available is "HEAD". Can you set it up?

**Comment by NZedPred** [comment]
> Hello, this will need to be pushed to our gerrit instance at gerrit.twrp.me for merging and review.

Hi @bigbiff - the android-9.0 branch isn't available on gerrit. I see the repository, but the only branch available is "HEAD". Can you set it up?

**Comment by bigbiff** [comment]
Hello, I was able to upload the project to gerrit. Please let me know if you have further issues.

**Comment by NZedPred** [comment]
I've gotten it into Gerrit a few days ago. Do I need to assign it to someone, or will it just be picked up in due course?

**Comment by bigbiff** [comment]
Hello, please assign it to me for review.

**Pull request closed without merging**
